### ISSUE TITLE
Cannot test sample model and policy using the "in" special grammar

### ISSUE THREAD

**Issue by techarch** [casbin/casbin-editor#57]
I am having trouble using the "in" grammar extension mentioned in https://casbin.org/docs/en/syntax-for-models#special-grammer. I tried both in the Casbin editor and in a .NET program.
See [Example](https://casbin.org/casbin-editor/#4MZTYXUEE)
The validation passes but when I run it I get the following message: "value.trim is not a function"

Model:

```ini
[request_definition]
r = sub, obj, act

[policy_definition]
p = role, sub_rule, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act && p.role in (r.obj.Roles)
```

Policies:

```csv
p, Assistant, r.sub.Amount <= 5000, authorization, grant
p, Manager, r.sub.Amount > 5000, authorization, grant
```

Evaluation Data:
-------------------------------------------------------------------
{Amount: 5100, Roles: ["Manager"]}, authorization, grant

**Comment by hsluoyz** [comment]
@Zxilly @closetool @tangyang9464 @Gabriel-403 

/cc @nodece

**Comment by Zxilly** [comment]
have located the bug, will fix it tomorrow

**Comment by Zxilly** [comment]
This problem is caused by two reason, one is editor parse the object unexpectedly, I have made a patch to fix it.
The other bug is the node-casbin directly use the `in` of javascript, but `in` in javascript means search the prototype chain of object. It results to 
![image](https://user-images.githubusercontent.com/31370133/127432280-b86c8852-8a88-4d24-bce3-d27d6bc65edf.png)
Another patch on this will be sent to upstream.
